### ISSUE TITLE
Allow access to Settings in welcome

### ISSUE THREAD

**Issue by licaon-kter** [snikket-im/snikket-android#1]
...so one can eg. enable Tor access

Conversations allows this in the second screen.

_(note that I don't have an invitation so maybe this can be done in the next screen without ever connecting to the internet, close if so)_

**Comment by mwild1** [comment]
I expect to review the welcome screen again at some point, and this will be one of the issues to consider addressing (there are some related things I want to improve too) :+1:

**Comment by mimi89999** [comment]
You can also do that in Snikket in the account creation screen. If this becomes a popular request, maybe a checkbox for that should be added on the registrations screen, but I don't know anybody using Conversations or Snikket with Tor.

**Comment by licaon-kter** [comment]
@mimi89999 Yup, indeed, thanks for the invitation. Looks fine.
