### ISSUE TITLE
Snikket notication always active no way to remove ?

### ISSUE THREAD

**Issue by wilecoyote2019** [snikket-im/snikket-android#14]
#### General information

* **Version:** 2.9.0+pcr
* **Device:** SAMSUNG A8
* **Android Version:**  8.0.0
* **Server name:** self hosted
* **Server software:** snikket 
* **Installed server modules: I can provide if necessary
* **Conversations source:** Sorry, don't know what to put here... 

This issue is not related with conversations. I installed a fresh server and some of my friends are using it. 
Several have a notification that is always displayed on the screen (1 account about 1 connected). 
My phone (the one described before) has this notifications and I cannot remove it.
But the issue is also present on other devices.

**Comment by mimi89999** [comment]
Hello,
You can long click the notification and open the notification settings. There you can disable that notification by disabling `Foreground service` notification category.

**Comment by wilecoyote2019** [comment]
Yep it worked for everybody in my team! Thanks with my congratulations for this great app!

**Comment by eloquence** [comment]
Ran into this issue on Android 16 on a Samsung device. Samsung's Android spin does not give access to notification categories unless you manually change the global system settings  (settings -> notifications, not the per-app settings). If you don't know this, Snikket's notification is impossible to remove without hiding _all_ notifications.

This is a pretty major UX issue and I would recommend reopening this issue to see if there is a better way to deal with the "connected" notification (does it even tell me anything useful as a user?).
