### ISSUE TITLE
Can you synchronize translations between platforms

### ISSUE THREAD

**Issue by mezysinc** [snikket-im/snikket-android#19]
#### General information

* **Version:** 2.6.0
* **Device:** Xiaomi Mi A1
* **Android Version:**  Android 9 (stock)
* **Server name:** conversations.im, jabber.at or self hosted
* **Server software:** ejabberd 19.09.1 or prosody 0.11.3 (if known)
* **Installed server modules:** Stream Managment, CSI, MAM
* **Conversations source:** PlayStore, PlayStore Beta Channel, F-Droid, self build (latest HEAD)

#### Steps to reproduce

1. …
2. …

#### Expected result

What is the expected output? 

#### Actual result

What do you see instead?

#### Debug output

Please post the output of adb logcat. The log should begin with the start of Conversations and include all the
steps it takes to reproduce the problem.

````
adb logcat -s conversations
````

**Comment by mezysinc** [comment]
It looks like they are now on weblate but before were on transifex, can you make ptbr strings available on weblate, missing ones like descriptions etc.

**Comment by mwild1** [comment]
Hi! We pull most translations from the Conversations project (which does use Transifex). Please contribute translations to that project, and they will be included in the next Snikket Android release.

There are a few strings that are [only present in Snikket](https://i18n.sotecware.net/projects/snikket/android-snikket-specific/). If you would like to contribute to that, please email team@snikket.org and we can set you up with an account there :)
