### ISSUE TITLE
Merge conflict marker in F-Droid app page

### ISSUE THREAD

**Issue by mlaradji** [snikket-im/snikket-android#2]
There seems to be a merge conflict marker in the app's description on the F-Droid page:
```
<<<<<<< HEAD
Snikket is an easy-to-use and privacy-friendly messaging app
======
``` 
The culprit file is https://github.com/snikket-im/snikket-android/blob/4934da6e1980f573cb064dcb0a66014c0a5b3249/fastlane/metadata/android/en-US/short_description.txt.

**Comment by mwild1** [comment]
Thanks! I just tagged a new release which should be picked up by F-Droid soon, and includes the fixed description.
