### ISSUE TITLE
Build in an EXIF scambler

### ISSUE THREAD

**Issue by MaxsimLionel** [snikket-im/snikket-android#37]
A user can enable this when first signing into their account from the app. An EXIF scrambling option that is set it and forget it. Any photos they send will have it's exif removed. I believe Signal had/has this built into this mobile clients.

**Comment by mwild1** [comment]
Hi, thanks for the feature request. However, EXIF is already stripped when sending photos.

**Comment by MaxsimLionel** [comment]
Thank you, very good to know.
