### ISSUE TITLE
[Q] care to add features? 

### ISSUE THREAD

**Issue by ildar** [snikket-im/snikket-android#4]
Some features aren't accepted by @inputmice, e.g. https://github.com/iNPUTmice/Conversations/issues/1778 . Would you consider implementing such?

**Comment by mwild1** [comment]
Hi!

In general we are aiming to keep Snikket as close to Conversations as possible. Good things should go into Conversations!

Specifically about the issue you linked, it is surprisingly complex to do properly. I also note that it was **not** explicitly rejected.

I would certainly like to see previews added at some point, and it will be something we can work on doing in a standard and privacy-friendly way, and in Conversations. One of the first steps would be drafting a general protocol for this and submitting it to the XSF. It's something I can do, but probably not before the end of the year as I have higher priorities to get Snikket off the ground :)

It will likely also depend on some code reorganisation that is planned to happen in Conversations.

I hope this answers your question. I'll close the issue, but that doesn't mean the feature you want won't happen in the future, it just means it's not a priority for Snikket right now and it needs to happen in Conversations first.
