### ISSUE TITLE
Separation of accounts' contacts and bookmarks

### ISSUE THREAD

**Issue by MaxsimLionel** [snikket-im/snikket-android#40]
I would love to see a clear separation or indication of which contact and bookmarks belong to which accounts. Blabber.im has an option for this that needs to be enabled, but it labels each one with the JID. A more easy to look at way of doing this could be to group them. Maybe also with collapsibility. All contacts from one account under one tab with the account JID, with a carrot, you can tap that to collapse it and see the next grouping.

**Comment by mwild1** [comment]
We're currently working on enhancing the contacts and multi-account UI with designers at Simply Secure.

**Comment by mwild1** [comment]
As this is already covered by other work in progress, I'm going to close the issue. That doesn't mean we won't be updating the UI.

**Comment by MaxsimLionel** [comment]
Nice, thank you.
